# Generated by Django 3.2 on 2021-04-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_filemanagetable_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagetable',
            name='decodekey',
            field=models.CharField(default='sssssss', max_length=50),
            preserve_default=False,
        ),
    ]
