# Generated by Django 3.2 on 2021-04-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_filemanagetable_decodekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('hashkey', models.CharField(max_length=200)),
                ('expire', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
